### ISSUE TITLE
it.equal_to is not a function - NodeJS

### ISSUE THREAD

**Issue by ScottShannon** [betterwaysystems/packer#10]
I was successfully using this package for a few days, but when I installed all of my npm dependencies on a different system I started getting errors.  Nothing changed in package.json and my first copy was still working fine until I cleared /node_modules and npm install, which gave me the same errors afterward.  Has something changed with one of this projects dependencies that could have broken it?  I even created a blank project and followed the example in this repos readme, but I get the same error.

Node - tested on 4.2.2 and 6.5.0

Error: 
```
Warning: Invalid argument supplied to oneOf, expected an instance of array.
/Users/{user}/Projects/{project}/node_modules/3d-bin-packing/release/node/packer.js:318
                for (var it = this.layer_map.begin(); !it.equal_to(this.layer_map.end()); it = it.next()) {
                                                          ^

TypeError: it.equal_to is not a function
    at Boxologic.iterate_orientations (/Users/{user}/Projects/{project}/node_modules/3d-bin-packing/release/node/packer.js:318:59)
    at Boxologic.pack (/Users/{user}/Projects/{project}/node_modules/3d-bin-packing/release/node/packer.js:302:18)
    at WrapperGroup.pack (/Users/{user}/Projects/{project}/node_modules/3d-bin-packing/release/node/packer.js:3553:39)
    at WrapperGroup.optimize (/Users/{user}/Projects/{project}/node_modules/3d-bin-packing/release/node/packer.js:3537:42)
    at Packer.initGenes (/Users/{user}/Projects/{project}/node_modules/3d-bin-packing/release/node/packer.js:1952:34)
    at Packer.optimize (/Users/{user}/Projects/{project}/node_modules/3d-bin-packing/release/node/packer.js:1859:42)
    at main (/Users/{user}/Projects/{project}/index.js:29:28)
    at Object.<anonymous> (/Users/{user}/Projects/{project}/index.js:37:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by samchon** [comment]
Update to v1.0.6, then the error will be fixed.

**Comment by ScottShannon** [comment]
That did the trick, thank you.
